name: Build index.json for Ksing repo

on:
  push:
    branches: [ "main" ]
    paths:
      - "packages/**"
      - "scripts/build_index.py"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate index.json
        run: python scripts/build_index.py

      - name: Commit index.json
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add index.json
          git commit -m "Automated index.json update" || echo "No changes to commit"
          git push
